version: "3.1"

services:
  db:
    image: mysql 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example 
      MYSQL_USER: nimish
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: springboot
    ports: 
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
